"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { CirclePlay, Clock3, FileDown, Goal, Minus, Pause, Plus, RotateCcw, Save, Swords, Trophy } from "lucide-react";
import { useAuth } from "@/components/providers/auth-provider";
import { useBaba } from "@/components/providers/baba-provider";
import type { ManualTeamResult, Player, Team } from "@/lib/domain/types";
import { EmptyState, ScreenHeading } from "@/components/ui/screen";

function StepNumber({ label, value, disabled, onChange }: { label: string; value: number; disabled: boolean; onChange(value: number): void }) {
  return <label className="step-number"><span>{label}</span><span><button type="button" disabled={disabled || value <= 0} onClick={() => onChange(Math.max(0, value - 1))} aria-label={`Diminuir ${label}`}><Minus /></button><input type="number" min={0} max={999} value={value} disabled={disabled} onChange={(event) => onChange(Math.max(0, Math.min(999, Math.trunc(Number(event.target.value) || 0))))} /><button type="button" disabled={disabled || value >= 999} onClick={() => onChange(Math.min(999, value + 1))} aria-label={`Aumentar ${label}`}><Plus /></button></span></label>;
}

function ManualTeamEditor({ team, players, initial, readOnly, onSave }: { team: Team; players: Player[]; initial?: ManualTeamResult; readOnly: boolean; onSave(result: ManualTeamResult): Promise<void> }) {
  const [wins, setWins] = useState(initial?.wins || 0); const [draws, setDraws] = useState(initial?.draws || 0); const [losses, setLosses] = useState(initial?.losses || 0);
  const [goals, setGoals] = useState<Record<string, number>>(initial?.goalsByPlayer || {}); const [saving, setSaving] = useState(false);
  const goalsFor = Object.values(goals).reduce((sum, value) => sum + value, 0);
  return <article className="card manual-result-card" style={{ "--team": team.color } as React.CSSProperties}><header><div><p className="eyebrow">{team.name}</p><h2>{wins * 3 + draws} pontos · {goalsFor} gols</h2></div>{initial && <span className="badge">Salvo</span>}</header><div className="manual-totals"><StepNumber label="Vitórias" value={wins} disabled={readOnly} onChange={setWins} /><StepNumber label="Empates" value={draws} disabled={readOnly} onChange={setDraws} /><StepNumber label="Derrotas" value={losses} disabled={readOnly} onChange={setLosses} /></div><div className="manual-scorers"><strong>Gols por jogador</strong>{players.map((player) => <StepNumber key={player.id} label={`${player.name}${player.type === "goleiro" ? " · GOL" : ""}`} value={goals[player.id] || 0} disabled={readOnly} onChange={(value) => setGoals((current) => ({ ...current, [player.id]: value }))} />)}</div>{!readOnly && <button className="button primary full" disabled={saving} onClick={async () => { setSaving(true); try { await onSave({ teamId: team.id, wins, draws, losses, goalsByPlayer: goals, updatedAtMs: Date.now() }); } finally { setSaving(false); } }}><Save /> {saving ? "Salvando…" : "Salvar totais do time"}</button>}</article>;
}

export function LiveScreen() {
  const { role } = useAuth(); const baba = useBaba(); const [tick, setTick] = useState(() => Date.now()); const [goalTeam, setGoalTeam] = useState<string | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const endSoundPlayed = useRef(false);
  const game = useMemo(() => baba.games.find((item) => item.id === baba.activeBaba?.currentGameId) || [...baba.games].reverse().find((item) => item.status !== "finished") || null, [baba.games, baba.activeBaba?.currentGameId]);
  useEffect(() => { if (game?.status !== "running") return; const id = window.setInterval(() => setTick(Date.now()), 1000); return () => window.clearInterval(id); }, [game?.status]);
  useEffect(() => {
    if (game?.status !== "running" || role !== "organizer" || !("wakeLock" in navigator)) return;
    let sentinel: { release(): Promise<void> } | null = null;
    const request = async () => { try { sentinel = await (navigator as Navigator & { wakeLock: { request(type: "screen"): Promise<{ release(): Promise<void> }> } }).wakeLock.request("screen"); } catch { /* Wake Lock é melhoria opcional. */ } };
    void request();
    return () => { void sentinel?.release(); };
  }, [game?.status, role]);
  const remaining = game ? Math.max(0, game.timerRemainingSeconds - (game.status === "running" && game.timerStartedAtMs ? Math.floor((tick - game.timerStartedAtMs) / 1000) : 0)) : 0;
  useEffect(() => { if (remaining > 0) endSoundPlayed.current = false; if (remaining === 0 && game?.status === "running" && !endSoundPlayed.current) { endSoundPlayed.current = true; setMessage("Tempo encerrado. Confirme o placar e finalize o jogo."); } }, [remaining, game?.status]);
  const run = async (operation: () => Promise<void>, success: string) => { setError(""); try { await operation(); setMessage(success); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível concluir."); } };

  if (!baba.activeBaba) return <><ScreenHeading eyebrow="Ao vivo" title="A quadra começa aqui" description="Quando o organizador iniciar o baba, tudo aparece em tempo real." /><EmptyState icon={<CirclePlay />} title="Nenhum baba em andamento" text={role === "organizer" ? "Inicie o encontro e marque as presenças no painel do organizador." : "Aguarde o organizador iniciar o próximo baba."} action={role === "organizer" && <Link className="button primary" href="/organizador">Abrir painel</Link>} /></>;

  if (baba.activeBaba.matchMode === "manual") {
    const playerById = new Map(baba.players.map((player) => [player.id, player]));
    return <><ScreenHeading eyebrow="Modo Manual" title="Totais do baba" description="Informe vitórias, empates, derrotas e gols. A tabela e o ranking usam somente estes totais salvos." action={<Link className="button secondary" href="/app/ficha-manual"><FileDown /> Ficha em branco</Link>} />{!baba.teams.length ? <EmptyState icon={<Swords />} title="Monte os times primeiro" text="Marque presenças e sorteie ou crie os times manualmente." action={<Link className="button primary" href="/app/times">Abrir times</Link>} /> : <div className="manual-results-grid">{baba.teams.map((team) => <ManualTeamEditor key={`${team.id}-${baba.manualResults.find((item) => item.teamId === team.id)?.updatedAtMs || 0}`} team={team} players={team.playerIds.map((id) => playerById.get(id)).filter((player): player is Player => Boolean(player))} initial={baba.manualResults.find((item) => item.teamId === team.id)} readOnly={role !== "organizer"} onSave={async (result) => { await baba.saveManualResult(result); setMessage(`${team.name} salvo sem duplicar estatísticas.`); }} />)}</div>}{role === "organizer" && baba.teams.length > 0 && <div className="manual-finish"><p>{baba.manualResults.length} de {baba.teams.length} times conferidos.</p><button className="button success" disabled={baba.manualResults.length !== baba.teams.length} onClick={() => run(baba.finishBaba, "Baba manual finalizado e agregado ao histórico.")}><Trophy /> Finalizar e salvar</button></div>}{(message || error) && <p className={`message ${error ? "error" : "success"}`} aria-live="polite">{error || message}</p>}</>;
  }

  const pending = baba.activeBaba.pendingTieBreak;
  if (pending) {
    const teamA = baba.teams.find((team) => team.id === pending.teamAId); const teamB = baba.teams.find((team) => team.id === pending.teamBId);
    return <><ScreenHeading eyebrow="Desempate pendente" title={pending.kind === "manual_odd_even" ? "Decida no ímpar ou par" : "Sortear quem permanece"} description="A próxima partida só pode ser preparada depois desta decisão." /><section className="card tie-break-card"><Swords /><h2>{teamA?.name || "Time A"} × {teamB?.name || "Time B"}</h2><p>{pending.kind === "manual_odd_even" ? "O organizador toca no vencedor do ímpar ou par. O terceiro time entra em seguida." : "Com somente dois times, o sistema usa aleatoriedade segura para definir a ordem."}</p>{role === "organizer" && (pending.kind === "manual_odd_even" ? <div><button className="button primary" onClick={() => run(() => baba.resolveTieBreak(pending.teamAId), `${teamA?.name} permanece.`)}>{teamA?.name}</button><button className="button primary" onClick={() => run(() => baba.resolveTieBreak(pending.teamBId), `${teamB?.name} permanece.`)}>{teamB?.name}</button></div> : <button className="button primary" onClick={() => run(() => baba.resolveTieBreak(), "Desempate sorteado. Próxima partida liberada.")}><RotateCcw /> Sortear quem fica</button>)}</section>{(message || error) && <p className={`message ${error ? "error" : "success"}`} aria-live="polite">{error || message}</p>}</>;
  }

  if (!game) return <><ScreenHeading eyebrow="Ao vivo" title="Times prontos para jogar" description="A próxima partida ainda não foi preparada." />{role === "organizer" ? <EmptyState icon={<Goal />} title="Prepare a próxima partida" text={baba.games.length ? "O rodízio salvo define os dois próximos times." : "O primeiro jogo será Time 1 × Time 2."} action={<button className="button primary" onClick={() => run(() => baba.prepareGame(), "Partida preparada. O cronômetro ainda não iniciou.")}>Preparar partida</button>} /> : <EmptyState icon={<Clock3 />} title="Aguardando a próxima partida" text="Esta tela atualizará automaticamente." />}</>;

  const teamPlayers = (teamId: string) => { const ids = teamId === game.teamAId ? game.rosterA : game.rosterB; return [...baba.players.filter((player) => ids.includes(player.id))].sort((a, b) => Number(b.type === "goleiro") - Number(a.type === "goleiro")); };
  return <div className="live-screen"><ScreenHeading eyebrow={`Jogo ${game.sequence}`} title={game.status === "running" ? "Partida em andamento" : game.status === "paused" ? "Jogo pausado" : "Partida preparada"} description="Placar e eventos sincronizados em tempo real." />
    <section className="scoreboard" aria-live="polite"><div className="timer"><Clock3 /><strong>{String(Math.floor(remaining / 60)).padStart(2, "0")}:{String(remaining % 60).padStart(2, "0")}</strong><span>{game.status === "running" ? "Jogando" : game.status === "paused" ? "Pausado" : "Pronto"}</span></div><div className="score-line"><button disabled={role !== "organizer" || game.status === "prepared" || game.status === "finished"} onClick={() => setGoalTeam(game.teamAId)} style={{ "--team": baba.teams.find((team) => team.id === game.teamAId)?.color } as React.CSSProperties}><span>{game.teamAName}</span><strong>{game.scoreA}</strong><small>{game.status === "prepared" ? "Inicie o jogo" : "Toque para gol"}</small></button><b>×</b><button disabled={role !== "organizer" || game.status === "prepared" || game.status === "finished"} onClick={() => setGoalTeam(game.teamBId)} style={{ "--team": baba.teams.find((team) => team.id === game.teamBId)?.color } as React.CSSProperties}><span>{game.teamBName}</span><strong>{game.scoreB}</strong><small>{game.status === "prepared" ? "Inicie o jogo" : "Toque para gol"}</small></button></div></section>
    {goalTeam && role === "organizer" && <section className="goal-picker"><div><p className="eyebrow">Quem marcou?</p><h2>{goalTeam === game.teamAId ? game.teamAName : game.teamBName}</h2></div><div className="player-choice-grid">{teamPlayers(goalTeam).map((player) => <button key={player.id} onClick={() => { void run(() => baba.addGoal(goalTeam, player.id), `Gol de ${player.name}.`); setGoalTeam(null); }}><span className="avatar">{player.name.slice(0, 2).toUpperCase()}</span><strong>{player.name}</strong><small>{player.type === "goleiro" ? "Goleiro" : "Linha"}</small></button>)}<button onClick={() => { void run(() => baba.addGoal(goalTeam, null), "Gol sem artilheiro."); setGoalTeam(null); }}><span className="avatar muted">—</span><strong>Sem artilheiro</strong><small>Jogador de fora</small></button></div><button className="text-button" onClick={() => setGoalTeam(null)}>Cancelar</button></section>}
    {role === "organizer" && <div className="live-actions"><button className="button primary" onClick={() => run(baba.startOrPauseGame, game.status === "running" ? "Jogo pausado." : "Cronômetro iniciado.")}>{game.status === "running" ? <><Pause /> Pausar</> : <><CirclePlay /> {game.status === "paused" ? "Retomar" : "Iniciar jogo"}</>}</button><button className="button secondary" disabled={!game.goalEvents.length} onClick={() => run(baba.undoGoal, "Último gol desfeito.")}><RotateCcw /> Desfazer gol</button><button className="button success" onClick={() => { if (window.confirm(`Finalizar ${game.teamAName} ${game.scoreA} × ${game.scoreB} ${game.teamBName}?`)) void run(baba.finishGame, "Jogo salvo. A próxima decisão foi preparada."); }}><Trophy /> Finalizar jogo</button></div>}
    {game.goalEvents.length > 0 && <section className="card"><h2>Gols da partida</h2><div className="event-list">{[...game.goalEvents].reverse().map((goal) => <div key={goal.id}><span className="event-dot" /><strong>{goal.playerNameSnapshot}</strong><small>{goal.minute}&apos; · {goal.teamId === game.teamAId ? game.teamAName : game.teamBName}</small></div>)}</div></section>}
    {(message || error) && <p className={`message ${error ? "error" : "success"}`} aria-live="polite">{error || message}</p>}
  </div>;
}
