"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { CirclePlay, Clock3, Goal, Pause, RotateCcw, Trophy } from "lucide-react";
import { useAuth } from "@/components/providers/auth-provider";
import { useBaba } from "@/components/providers/baba-provider";
import { EmptyState, ScreenHeading } from "@/components/ui/screen";

export function LiveScreen() {
  const { role } = useAuth(); const baba = useBaba(); const [tick, setTick] = useState(() => Date.now()); const [goalTeam, setGoalTeam] = useState<string | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const game = useMemo(() => baba.games.find((item) => item.id === baba.activeBaba?.currentGameId) || [...baba.games].reverse().find((item) => item.status !== "finished") || null, [baba.games, baba.activeBaba?.currentGameId]);
  useEffect(() => { if (game?.status !== "running") return; const id = window.setInterval(() => setTick(Date.now()), 1000); return () => window.clearInterval(id); }, [game?.status]);
  const remaining = game ? Math.max(0, game.timerRemainingSeconds - (game.status === "running" && game.timerStartedAtMs ? Math.floor((tick - game.timerStartedAtMs) / 1000) : 0)) : 0;
  const run = async (operation: () => Promise<void>, success: string) => { setError(""); try { await operation(); setMessage(success); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível concluir."); } };
  if (!baba.activeBaba) return <><ScreenHeading eyebrow="Ao vivo" title="A quadra começa aqui" description="Quando o organizador iniciar o baba, tudo aparece em tempo real." /><EmptyState icon={<CirclePlay />} title="Nenhum baba em andamento" text={role === "organizer" ? "Inicie o encontro e marque as presenças no painel do organizador." : "Aguarde o organizador iniciar o próximo baba."} action={role === "organizer" && <Link className="button primary" href="/organizador">Abrir painel</Link>} /></>;
  if (!game) return <><ScreenHeading eyebrow="Ao vivo" title="Times prontos para jogar" description="A próxima partida ainda não foi preparada." />{role === "organizer" ? <EmptyState icon={<Goal />} title="Prepare a primeira partida" text="O primeiro jogo será Time 1 × Time 2." action={<button className="button primary" onClick={() => run(() => baba.prepareGame(), "Partida preparada.")}>Preparar partida</button>} /> : <EmptyState icon={<Clock3 />} title="Aguardando a próxima partida" text="Esta tela atualizará automaticamente." />}</>;
  const teamPlayers = (teamId: string) => { const ids = teamId === game.teamAId ? game.rosterA : game.rosterB; return [...baba.players.filter((player) => ids.includes(player.id))].sort((a, b) => (a.type === "goleiro" ? -1 : 1) - (b.type === "goleiro" ? -1 : 1)); };
  return <div className="live-screen"><ScreenHeading eyebrow={`Jogo ${game.sequence}`} title={game.status === "running" ? "Partida em andamento" : game.status === "paused" ? "Jogo pausado" : "Partida preparada"} description="Placar e eventos sincronizados em tempo real." />
    <section className="scoreboard" aria-live="polite"><div className="timer"><Clock3 /><strong>{String(Math.floor(remaining / 60)).padStart(2, "0")}:{String(remaining % 60).padStart(2, "0")}</strong><span>{game.status === "running" ? "Jogando" : game.status === "paused" ? "Pausado" : "Pronto"}</span></div><div className="score-line"><button disabled={role !== "organizer"} onClick={() => setGoalTeam(game.teamAId)} style={{ "--team": baba.teams.find((team) => team.id === game.teamAId)?.color } as React.CSSProperties}><span>{game.teamAName}</span><strong>{game.scoreA}</strong><small>Toque para gol</small></button><b>×</b><button disabled={role !== "organizer"} onClick={() => setGoalTeam(game.teamBId)} style={{ "--team": baba.teams.find((team) => team.id === game.teamBId)?.color } as React.CSSProperties}><span>{game.teamBName}</span><strong>{game.scoreB}</strong><small>Toque para gol</small></button></div></section>
    {goalTeam && role === "organizer" && <section className="goal-picker"><div><p className="eyebrow">Quem marcou?</p><h2>{goalTeam === game.teamAId ? game.teamAName : game.teamBName}</h2></div><div className="player-choice-grid">{teamPlayers(goalTeam).map((player) => <button key={player.id} onClick={() => { run(() => baba.addGoal(goalTeam, player.id), `Gol de ${player.name}.`); setGoalTeam(null); }}><span className="avatar">{player.name.slice(0, 2).toUpperCase()}</span><strong>{player.name}</strong><small>{player.type === "goleiro" ? "Goleiro" : "Linha"}</small></button>)}<button onClick={() => { run(() => baba.addGoal(goalTeam, null), "Gol sem artilheiro."); setGoalTeam(null); }}><span className="avatar muted">—</span><strong>Sem artilheiro</strong><small>Jogador de fora</small></button></div><button className="text-button" onClick={() => setGoalTeam(null)}>Cancelar</button></section>}
    {role === "organizer" && <div className="live-actions"><button className="button primary" onClick={() => run(baba.startOrPauseGame, game.status === "running" ? "Jogo pausado." : "Cronômetro iniciado.")}>{game.status === "running" ? <><Pause /> Pausar</> : <><CirclePlay /> {game.status === "paused" ? "Retomar" : "Iniciar jogo"}</>}</button><button className="button secondary" disabled={!game.goalEvents.length} onClick={() => run(baba.undoGoal, "Último gol desfeito.")}><RotateCcw /> Desfazer gol</button><button className="button success" onClick={() => run(baba.finishGame, "Jogo salvo. Próxima partida pronta para preparar.")}><Trophy /> Finalizar jogo</button></div>}
    {game.goalEvents.length > 0 && <section className="card"><h2>Gols da partida</h2><div className="event-list">{[...game.goalEvents].reverse().map((goal) => <div key={goal.id}><span className="event-dot" /><strong>{goal.playerNameSnapshot}</strong><small>{goal.minute}&apos; · {goal.teamId === game.teamAId ? game.teamAName : game.teamBName}</small></div>)}</div></section>}
    {(message || error) && <p className={`message ${error ? "error" : "success"}`} aria-live="polite">{error || message}</p>}
  </div>;
}
