"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { CalendarDays, ClipboardList, Download, LogOut, Palette, Printer, Target } from "lucide-react";
import { useAuth } from "@/components/providers/auth-provider";
import { useBaba } from "@/components/providers/baba-provider";
import { ScreenHeading } from "@/components/ui/screen";

export function MoreScreen() { const auth = useAuth(); const baba = useBaba(); const router = useRouter(); const backup = () => { const payload = JSON.stringify({ schemaVersion: 3, exportedAt: new Date().toISOString(), players: baba.players, babas: baba.babas, teams: baba.teams, games: baba.games }, null, 2); const href = URL.createObjectURL(new Blob([payload], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = href; anchor.download = `baba-psyzon-backup-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(href); }; return <><ScreenHeading eyebrow="Mais opções" title="Tudo do seu baba" description="Histórico, metas, aparência, arquivos e acesso." /><div className="menu-grid"><Link href="/app/historico"><span><CalendarDays /></span><div><strong>Histórico</strong><small>Veja os babas finalizados</small></div></Link><Link href="/app/metas"><span><Target /></span><div><strong>Metas de compra</strong><small>Equipamentos e arrecadação</small></div></Link><Link href="/mesa-tatica"><span><ClipboardList /></span><div><strong>Mesa tática</strong><small>Monte e salve jogadas</small></div></Link><Link href="/aparencia"><span><Palette /></span><div><strong>Aparência</strong><small>Tema, densidade e animações</small></div></Link><button onClick={() => window.print()}><span><Printer /></span><div><strong>Imprimir / PDF</strong><small>Salve a tela atual em PDF</small></div></button>{auth.role === "organizer" && <button onClick={backup}><span><Download /></span><div><strong>Exportar backup</strong><small>Baixar dados atuais em JSON</small></div></button>}<button className="logout-item" onClick={async () => { await auth.logout(); router.replace("/"); }}><span><LogOut /></span><div><strong>Sair / trocar acesso</strong><small>Voltar para a tela inicial</small></div></button></div></>; }
