"use client";

import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { CalendarPlus, Check, ChevronRight, CircleDollarSign, KeyRound, Plus, ShieldCheck, Shuffle, Trophy, UserPlus, UsersRound } from "lucide-react";
import { useAuth } from "@/components/providers/auth-provider";
import { useBaba } from "@/components/providers/baba-provider";
import { monthlyPriceCents, paymentSummary } from "@/lib/domain/payments";
import { ScreenHeading, StatCard } from "@/components/ui/screen";
const money = (cents: number) => (cents / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

export function OrganizerScreen() {
  const auth = useAuth(); const baba = useBaba(); const router = useRouter(); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [name, setName] = useState(""); const [type, setType] = useState<"linha" | "goleiro">("linha"); const [code, setCode] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const payment = paymentSummary(baba.players);
  useEffect(() => { if (!auth.loading && auth.role !== "organizer") router.replace("/app/ao-vivo"); }, [auth.loading, auth.role, router]);
  if (!auth.loading && auth.role !== "organizer") return null;
  const run = async (operation: () => Promise<unknown>, success: string) => { setError(""); try { await operation(); setMessage(success); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível concluir."); } };
  const present = baba.players.filter((player) => player.present); const step = !baba.activeBaba ? 0 : !baba.teams.length ? 1 : baba.games.length === 0 ? 2 : 3;
  return <div className="standalone-content"><ScreenHeading eyebrow="Painel do organizador" title="Qual é o próximo passo?" description="O painel destaca somente o que precisa de atenção agora." action={<span className="role-chip"><ShieldCheck /> Acesso completo</span>} />
    <ol className="stepper" aria-label="Etapas do baba">{["Presenças", "Modo", "Sorteio", "Partidas", "Finalizar"].map((label, index) => <li key={label} className={index < step ? "done" : index === step ? "current" : ""}><span>{index < step ? <Check /> : index + 1}</span><small>{label}</small></li>)}</ol>
    {!baba.activeBaba ? <section className="primary-task"><span className="task-icon"><CalendarPlus /></span><div><p className="eyebrow">Próxima ação</p><h2>Inicie o baba de hoje</h2><p>Você poderá editar a data antes de finalizar.</p></div><label>Data do baba<input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><button className="button primary" onClick={() => run(() => baba.createBaba(date), "Baba iniciado. Marque as presenças.")}>Iniciar novo baba <ChevronRight /></button></section> : !baba.teams.length ? <section className="primary-task"><span className="task-icon"><UsersRound /></span><div><p className="eyebrow">Próxima ação</p><h2>Marque quem está presente</h2><p>{present.length} selecionados · {present.filter((item) => item.type === "linha").length} jogadores de linha</p></div><div className="segmented" aria-label="Modo de anotação"><button className={baba.activeBaba.matchMode === "online" ? "active" : ""} onClick={() => run(() => baba.setMode("online"), "Modo pelo site selecionado.")}>Pelo site</button><button className={baba.activeBaba.matchMode === "manual" ? "active" : ""} onClick={() => run(() => baba.setMode("manual"), "Modo manual selecionado.")}>Manual</button></div><button className="button primary" disabled={present.filter((item) => item.type === "linha" && item.status !== "convidado").length < 8} onClick={() => run(baba.draw, "Times sorteados.")}><Shuffle /> Sortear times</button><button className="button secondary" onClick={() => router.push("/app/times")}>Abrir lista de presenças</button></section> : <section className="primary-task"><span className="task-icon"><Trophy /></span><div><p className="eyebrow">Próxima ação</p><h2>{baba.activeBaba.currentGameId ? "Controle a partida" : baba.games.length ? "Prepare o próximo jogo" : "Prepare o primeiro jogo"}</h2><p>{baba.teams.length} times · {baba.games.filter((game) => game.status === "finished").length} jogos concluídos</p></div><button className="button primary" onClick={() => baba.activeBaba?.currentGameId ? router.push("/app/ao-vivo") : run(() => baba.prepareGame(), "Partida preparada.")}>{baba.activeBaba.currentGameId ? "Abrir placar ao vivo" : "Preparar próxima partida"}<ChevronRight /></button><button className="button success" onClick={() => { if (window.confirm("Finalizar este baba? Os dados serão guardados no histórico.")) run(baba.finishBaba, "Baba finalizado e salvo no histórico."); }}><Trophy /> Finalizar baba</button></section>}
    <div className="admin-grid"><section className="card"><div className="card-title-row"><div><h2>Jogadores</h2><p>{baba.players.length} cadastrados</p></div><UserPlus /></div><form className="quick-form" onSubmit={(event) => { event.preventDefault(); if (!name.trim()) return; run(() => baba.addPlayer(name, type), `${name} foi cadastrado.`); setName(""); }}><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Nome do jogador" maxLength={60} aria-label="Nome do jogador" /><select value={type} onChange={(event) => setType(event.target.value as "linha" | "goleiro")} aria-label="Tipo"><option value="linha">Linha</option><option value="goleiro">Goleiro</option></select><button className="button primary" aria-label="Adicionar jogador"><Plus /></button></form><div className="compact-player-list">{baba.players.slice(0, 8).map((player) => <div key={player.id}><span className="avatar">{player.name.slice(0, 2).toUpperCase()}</span><span><strong>{player.name}</strong><small>{player.type} · {player.status}</small></span></div>)}{baba.players.length > 8 && <button className="text-button" onClick={() => router.push("/app/times")}>Ver todos</button>}</div></section>
      <section className="card"><div className="card-title-row"><div><h2>Pagamentos do mês</h2><p>Vencimento dia 10</p></div><CircleDollarSign /></div><div className="stat-grid mini"><StatCard label="Recebido" value={money(payment.paidCents)} /><StatCard label="Pendente" value={money(payment.expectedCents - payment.paidCents)} /></div><div className="payment-list">{baba.players.filter((player) => monthlyPriceCents(player) > 0).map((player) => <button key={player.id} onClick={() => baba.togglePayment(player.id)}><span>{player.name}<small>{money(monthlyPriceCents(player))}</small></span><strong className={player.paid ? "paid" : "pending"}>{player.paid ? "Pago" : "Pendente"}</strong></button>)}</div></section>
      <section className="card access-code-card"><div className="card-title-row"><div><h2>Código dos jogadores</h2><p>Somente leitura</p></div><KeyRound /></div>{code ? <div className="generated-code"><span>{code}</span><p>Compartilhe estes quatro dígitos com os jogadores.</p><button className="button secondary" onClick={() => navigator.clipboard.writeText(code)}>Copiar código</button></div> : <button className="button primary full" onClick={async () => { const nextCode = await baba.generateViewerCode(); setCode(nextCode); setMessage("Código gerado com segurança."); }}><KeyRound /> Gerar / rotacionar código</button>}</section>
      {baba.activeBaba && <section className="card danger-zone"><h2>Ações do baba atual</h2><p>O histórico finalizado nunca é apagado por esta ação.</p><button className="button danger" onClick={() => { if (window.confirm("Resetar somente o baba atual? Esta ação preserva o histórico.")) run(baba.resetActiveBaba, "Baba atual resetado."); }}>Resetar baba atual</button></section>}
    </div>{(message || error) && <p className={`message floating-message ${error ? "error" : "success"}`} aria-live="polite">{error || message}</p>}
  </div>;
}
