"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { CalendarPlus, Check, ChevronRight, CircleDollarSign, Copy, KeyRound, LockKeyhole, Plus, RefreshCw, ShieldCheck, Shuffle, Trophy, UserPlus, UsersRound } from "lucide-react";
import { useAuth } from "@/components/providers/auth-provider";
import { useBaba } from "@/components/providers/baba-provider";
import { monthlyPriceCents, paymentSummary } from "@/lib/domain/payments";
import { ScreenHeading, StatCard } from "@/components/ui/screen";

const money = (cents: number) => (cents / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

export function OrganizerScreen() {
  const auth = useAuth(); const baba = useBaba(); const router = useRouter(); const [date, setDate] = useState(() => new Date().toLocaleDateString("en-CA", { timeZone: "America/Bahia" })); const [name, setName] = useState(""); const [type, setType] = useState<"linha" | "goleiro">("linha"); const [code, setCode] = useState(""); const [commissionPassword, setCommissionPassword] = useState(""); const [commissionConfirmation, setCommissionConfirmation] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const payment = paymentSummary(baba.players, baba.payments); const paymentById = useMemo(() => new Map(baba.payments.map((item) => [item.playerId, item.status])), [baba.payments]);
  useEffect(() => { if (!auth.loading && auth.role !== "organizer") router.replace("/app/ao-vivo"); }, [auth.loading, auth.role, router]);
  const getViewerCode = baba.getViewerCode;
  useEffect(() => { if (auth.role === "organizer") void getViewerCode().then((value) => setCode(value || "")).catch(() => undefined); }, [auth.role, getViewerCode]);
  if (!auth.loading && auth.role !== "organizer") return null;
  const run = async (operation: () => Promise<unknown>, success: string) => { setBusy(true); setError(""); setMessage(""); try { await operation(); setMessage(success); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível concluir."); } finally { setBusy(false); } };
  const saveCommissionPassword = async () => {
    if (!auth.user?.email) throw new Error("Sua conta Google não possui e-mail disponível.");
    const token = await auth.organizerToken();
    const response = await fetch("/api/commission", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ email: auth.user.email, password: commissionPassword, confirmation: commissionConfirmation }) });
    const data = await response.json().catch(() => ({})) as { error?: string };
    if (!response.ok) throw new Error(data.error || "Não foi possível atualizar a senha da comissão.");
    setCommissionPassword(""); setCommissionConfirmation("");
  };
  const present = baba.players.filter((player) => player.active && player.present); const fieldCount = present.filter((item) => item.type === "linha" && item.status !== "convidado").length; const finishedGames = baba.games.filter((game) => game.status === "finished").length;
  const step = !baba.activeBaba ? 0 : !present.length ? 0 : !baba.teams.length ? 1 : baba.activeBaba.matchMode === "manual" ? 3 : !baba.games.length ? 2 : 3;
  const stateLabel = !baba.activeBaba ? "Nenhum baba" : baba.activeBaba.pendingTieBreak ? "Desempate pendente" : baba.activeBaba.status === "open" ? "Aberto" : baba.activeBaba.status === "drawn" ? "Times sorteados" : baba.activeBaba.status === "playing" ? "Jogando" : "Preparado";

  return <div className="standalone-content"><ScreenHeading eyebrow="Organização do baba" title="Controle do Baba" description="Uma ação principal por estado, com as operações perigosas separadas." action={<span className="role-chip"><ShieldCheck /> {stateLabel}</span>} />
    <ol className="stepper five" aria-label="Etapas do baba">{["Presenças", "Modo", "Sorteio", "Partidas / estatísticas", "Finalizar"].map((label, index) => <li key={label} className={index < step ? "done" : index === step ? "current" : ""}><span>{index < step ? <Check /> : index + 1}</span><small>{label}</small></li>)}</ol>
    {!baba.activeBaba ? <section className="primary-task"><span className="task-icon"><CalendarPlus /></span><div><p className="eyebrow">Próxima ação</p><h2>Inicie o baba de hoje</h2><p>A data pode ser escolhida agora e fica salva em `pt-BR`.</p></div><label>Data do baba<input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><button className="button primary" disabled={busy || !date} onClick={() => run(() => baba.createBaba(date), "Baba iniciado. Marque as presenças.")}>Iniciar novo baba <ChevronRight /></button></section>
      : !baba.teams.length ? <section className="primary-task"><span className="task-icon"><UsersRound /></span><div><p className="eyebrow">Próxima ação</p><h2>Presenças, modo e sorteio</h2><p>{present.length} selecionados · {fieldCount} jogadores de linha · modo {baba.activeBaba.matchMode === "online" ? "Pelo Site" : "Manual"}</p></div><button className="button primary" disabled={busy || fieldCount < 8} onClick={() => run(baba.draw, "Times sorteados.")}><Shuffle /> Sortear times</button><button className="button secondary" onClick={() => router.push("/app/times")}>Editar presentes e modo</button></section>
      : <section className="primary-task"><span className="task-icon"><Trophy /></span><div><p className="eyebrow">Próxima ação</p><h2>{baba.activeBaba.pendingTieBreak ? "Resolva o desempate" : baba.activeBaba.matchMode === "manual" ? "Informe as estatísticas finais" : baba.activeBaba.currentGameId ? "Controle a partida" : baba.games.length ? "Prepare o próximo jogo" : "Prepare o primeiro jogo"}</h2><p>{baba.teams.length} times · {finishedGames} jogos concluídos · {baba.manualResults.length} totais manuais</p></div><button className="button primary" disabled={busy} onClick={() => baba.activeBaba?.matchMode === "manual" || baba.activeBaba?.currentGameId || baba.activeBaba?.pendingTieBreak ? router.push("/app/ao-vivo") : run(() => baba.prepareGame(), "Partida preparada sem iniciar o cronômetro.")}>{baba.activeBaba.matchMode === "manual" ? "Abrir totais manuais" : baba.activeBaba.currentGameId ? "Abrir placar ao vivo" : baba.activeBaba.pendingTieBreak ? "Resolver desempate" : "Preparar próxima partida"}<ChevronRight /></button><button className="button success" disabled={busy} onClick={() => { if (window.confirm("Finalizar este baba? Os dados serão recalculados e guardados no histórico.")) void run(baba.finishBaba, "Baba finalizado e salvo no histórico."); }}><Trophy /> Finalizar baba</button></section>}
    {baba.activeBaba && finishedGames > 0 && !baba.activeBaba.currentGameId && <div className="secondary-actions"><button className="button secondary" disabled={busy} onClick={() => { if (window.confirm("Desfazer somente o último jogo finalizado e restaurar tabela e fila?")) void run(baba.undoLastGame, "Último jogo restaurado para conferência."); }}>Desfazer último jogo</button></div>}

    <div className="admin-grid"><section className="card"><div className="card-title-row"><div><h2>Jogadores</h2><p>{baba.players.filter((player) => player.active).length} ativos · {baba.players.length} no histórico</p></div><UserPlus /></div><form className="quick-form" onSubmit={(event) => { event.preventDefault(); if (!name.trim()) return; const normalized = name.trim(); void run(() => baba.addPlayer(normalized, type), `${normalized} foi cadastrado.`).then(() => setName("")); }}><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Nome do jogador" maxLength={80} aria-label="Nome do jogador" /><select value={type} onChange={(event) => setType(event.target.value as "linha" | "goleiro")} aria-label="Tipo"><option value="linha">Linha</option><option value="goleiro">Goleiro</option></select><button className="button primary" disabled={busy || !name.trim()} aria-label="Adicionar jogador"><Plus /></button></form><div className="compact-player-list">{baba.players.filter((player) => player.active).slice(0, 8).map((player) => <div key={player.id}><span className="avatar">{player.name.slice(0, 2).toUpperCase()}</span><span><strong>{player.name}</strong><small>{player.type} · {player.status}</small></span></div>)}{baba.players.length > 8 && <Link className="text-button" href="/app/pagamentos">Gerenciar todos</Link>}</div></section>
      <section className="card"><div className="card-title-row"><div><h2>Pagamentos do mês</h2><p>Vencimento dia 10</p></div><CircleDollarSign /></div><div className="stat-grid mini"><StatCard label="Recebido" value={money(payment.paidCents)} /><StatCard label="Pendente" value={money(payment.expectedCents - payment.paidCents)} /></div><div className="payment-list">{baba.players.filter((player) => monthlyPriceCents(player) > 0).slice(0, 10).map((player) => { const paid = paymentById.get(player.id) === "paid"; return <button key={player.id} disabled={busy} onClick={() => void run(() => baba.togglePayment(player.id), `Pagamento de ${player.name} atualizado.`)}><span>{player.name}<small>{money(monthlyPriceCents(player))}</small></span><strong className={paid ? "paid" : "pending"}>{paid ? "Pago" : "Pendente"}</strong></button>; })}</div><Link className="button secondary full" href="/app/pagamentos">Gerenciar jogadores e pagamentos</Link></section>
      <section className="card access-code-card"><div className="card-title-row"><div><h2>Código dos jogadores</h2><p>Acesso de leitura · HMAC no servidor</p></div><KeyRound /></div>{code ? <div className="generated-code"><span>{code}</span><p>O código não fica em texto puro no banco. Rotacionar revoga as sessões anteriores.</p><div className="code-actions"><button className="button secondary" onClick={() => void navigator.clipboard.writeText(code).then(() => setMessage("Código copiado."))}><Copy /> Copiar</button><button className="button secondary" disabled={busy} onClick={() => void run(async () => { const current = await baba.getViewerCode(); setCode(current || ""); }, "Código recarregado do servidor.")}><RefreshCw /> Recarregar</button><button className="button danger" disabled={busy} onClick={() => { if (window.confirm("Rotacionar o código e revogar todos os acessos de jogador atuais?")) void run(async () => setCode(await baba.generateViewerCode()), "Código rotacionado. Sessões antigas revogadas."); }}><KeyRound /> Rotacionar</button></div></div> : <button className="button primary full" disabled={busy} onClick={() => void run(async () => setCode(await baba.generateViewerCode()), "Código criado com segurança.")}><KeyRound /> Criar código seguro</button>}</section>
      <section className="card"><div className="card-title-row"><div><h2>Acesso da comissão</h2><p>Mesmo e-mail e mesmos dados da conta</p></div><LockKeyhole /></div><p className="muted-copy">Entre recentemente pelo Google e defina uma senha forte. A senha fica somente no Firebase Authentication.</p><form className="commission-form" onSubmit={(event) => { event.preventDefault(); void run(saveCommissionPassword, "Senha da comissão atualizada."); }}><label>E-mail da conta<input type="email" value={auth.user?.email || ""} readOnly /></label><label>Nova senha<input type="password" autoComplete="new-password" minLength={12} maxLength={72} value={commissionPassword} onChange={(event) => setCommissionPassword(event.target.value)} placeholder="12+ caracteres, maiúscula e número" /></label><label>Confirmar nova senha<input type="password" autoComplete="new-password" minLength={12} maxLength={72} value={commissionConfirmation} onChange={(event) => setCommissionConfirmation(event.target.value)} /></label><button className="button primary full" disabled={busy || commissionPassword.length < 12 || commissionPassword !== commissionConfirmation}><LockKeyhole /> Criar ou trocar senha</button></form></section>
      {baba.activeBaba && <section className="card danger-zone"><h2>Ações do baba atual</h2><p>Reset encerra logicamente somente o encontro atual. Históricos finalizados permanecem intactos.</p><button className="button danger" disabled={busy} onClick={() => { if (window.confirm("Resetar somente o baba atual? Times e partidas deste encontro serão arquivados.")) void run(baba.resetActiveBaba, "Baba atual resetado."); }}>Resetar baba atual</button></section>}
    </div>{(message || error) && <p className={`message floating-message ${error ? "error" : "success"}`} aria-live="polite">{error || message}</p>}
  </div>;
}
