"use client";

import Link from "next/link";
import { ChangeEvent, useEffect, useRef, useState } from "react";
import { ArrowLeft, CircleDot, Download, Eraser, Maximize2, Plus, Redo2, Save, Undo2, Upload, UsersRound } from "lucide-react";

interface Marker { id: string; kind: "player" | "ball"; team: "blue" | "red"; name: string; number: number; x: number; y: number }
const initial: Marker[] = [
  { id: "b1", kind: "player", team: "blue", name: "Goleiro", number: 1, x: 12, y: 50 }, { id: "b2", kind: "player", team: "blue", name: "Fixo", number: 4, x: 28, y: 50 },
  { id: "r1", kind: "player", team: "red", name: "Goleiro", number: 1, x: 88, y: 50 }, { id: "r2", kind: "player", team: "red", name: "Fixo", number: 4, x: 72, y: 50 },
  { id: "ball", kind: "ball", team: "blue", name: "Bola", number: 0, x: 50, y: 50 },
];

export function TacticalBoard() { const [markers, setMarkers] = useState<Marker[]>(initial); const [history, setHistory] = useState<Marker[][]>([]); const [future, setFuture] = useState<Marker[][]>([]); const [selectedTeam, setSelectedTeam] = useState<"blue" | "red">("blue"); const board = useRef<HTMLDivElement>(null); const input = useRef<HTMLInputElement>(null); const dragging = useRef<string | null>(null);
  // The tactical board is intentionally restored from device-local autosave after hydration.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem("psyzon-tactical-board") || "null"); if (Array.isArray(saved)) setMarkers(saved.slice(0, 60)); } catch {} }, []);
  const commit = (next: Marker[]) => { setHistory((items) => [...items.slice(-39), markers]); setFuture([]); setMarkers(next); localStorage.setItem("psyzon-tactical-board", JSON.stringify(next)); };
  const position = (event: React.PointerEvent) => { const box = board.current!.getBoundingClientRect(); return { x: Math.max(2, Math.min(98, ((event.clientX - box.left) / box.width) * 100)), y: Math.max(3, Math.min(97, ((event.clientY - box.top) / box.height) * 100)) }; };
  const exportJson = () => { const href = URL.createObjectURL(new Blob([JSON.stringify({ schemaVersion: 1, markers }, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = href; link.download = "jogada-baba-psyzon.json"; link.click(); URL.revokeObjectURL(href); };
  const importJson = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || file.size > 1_000_000) return; try { const value = JSON.parse(await file.text()); if (!Array.isArray(value.markers) || value.markers.length > 60) throw new Error(); const clean = value.markers.map((item: Marker) => ({ id: String(item.id).slice(0, 80), kind: item.kind === "ball" ? "ball" : "player", team: item.team === "red" ? "red" : "blue", name: String(item.name || "Jogador").replace(/[<>]/g, "").slice(0, 30), number: Math.max(0, Math.min(99, Number(item.number) || 0)), x: Math.max(0, Math.min(100, Number(item.x))), y: Math.max(0, Math.min(100, Number(item.y))) })); commit(clean); } catch { window.alert("Arquivo de jogada inválido."); } event.target.value = ""; };
  return <main className="tactical-page"><header className="tactical-toolbar"><Link href="/" className="icon-button" aria-label="Voltar"><ArrowLeft /></Link><div><strong>Mesa tática</strong><small>Arraste os jogadores na quadra</small></div><button className="icon-button" aria-label="Tela cheia" onClick={() => document.documentElement.requestFullscreen?.()}><Maximize2 /></button></header>
    <div className="tactical-layout"><aside className="tool-panel"><div className="team-toggle"><button className={selectedTeam === "blue" ? "active blue" : ""} onClick={() => setSelectedTeam("blue")}>Azul</button><button className={selectedTeam === "red" ? "active red" : ""} onClick={() => setSelectedTeam("red")}>Vermelho</button></div><button onClick={() => commit([...markers, { id: crypto.randomUUID(), kind: "player", team: selectedTeam, name: "Jogador", number: markers.filter((item) => item.team === selectedTeam).length + 1, x: selectedTeam === "blue" ? 30 : 70, y: 25 + Math.random() * 50 }])}><Plus /><span>Jogador</span></button><button onClick={() => !markers.some((item) => item.kind === "ball") && commit([...markers, { id: "ball", kind: "ball", team: "blue", name: "Bola", number: 0, x: 50, y: 50 }])}><CircleDot /><span>Bola</span></button><button disabled={!history.length} onClick={() => { const previous = history.at(-1); if (previous) { setFuture((items) => [markers, ...items]); setMarkers(previous); setHistory((items) => items.slice(0, -1)); } }}><Undo2 /><span>Desfazer</span></button><button disabled={!future.length} onClick={() => { const next = future[0]; setHistory((items) => [...items, markers]); setMarkers(next); setFuture((items) => items.slice(1)); }}><Redo2 /><span>Refazer</span></button><button onClick={() => commit([])}><Eraser /><span>Limpar</span></button><button onClick={() => { localStorage.setItem("psyzon-tactical-board", JSON.stringify(markers)); }}><Save /><span>Salvar</span></button><button onClick={exportJson}><Download /><span>Exportar</span></button><button onClick={() => input.current?.click()}><Upload /><span>Importar</span></button><input ref={input} type="file" accept="application/json" hidden onChange={importJson} /></aside>
      <section className="court-wrap"><div ref={board} className="futsal-court" onPointerMove={(event) => { if (!dragging.current) return; const pos = position(event); setMarkers((items) => items.map((item) => item.id === dragging.current ? { ...item, ...pos } : item)); }} onPointerUp={() => { if (dragging.current) { dragging.current = null; localStorage.setItem("psyzon-tactical-board", JSON.stringify(markers)); } }}><div className="court-center" /><div className="court-circle" /><div className="area left" /><div className="area right" />{markers.map((marker) => <button key={marker.id} className={`marker ${marker.kind} ${marker.team}`} style={{ left: `${marker.x}%`, top: `${marker.y}%` }} onPointerDown={(event) => { event.currentTarget.setPointerCapture(event.pointerId); dragging.current = marker.id; }} onDoubleClick={() => { if (marker.kind === "ball") return; const name = window.prompt("Nome do jogador", marker.name); if (name) commit(markers.map((item) => item.id === marker.id ? { ...item, name: name.replace(/[<>]/g, "").slice(0, 30) } : item)); }} aria-label={`${marker.name}. Arraste para mover`}>{marker.kind === "ball" ? <CircleDot /> : <><strong>{marker.number}</strong><small>{marker.name}</small></>}</button>)}</div><p className="court-tip"><UsersRound /> Toque duas vezes em um jogador para editar o nome.</p></section></div>
  </main>;
}
